name: Deploy to Firebase Hosting on push

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm i -g firebase-tools

      # Statik site -> build yok. (İleride build gerekirse burada yaparsın.)

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project atlas-inventory-system --non-interactive --token "${{ secrets.FIREBASE_TOKEN }}"
